### ISSUE TITLE
服务端玩家进入不了游戏，直接报下面这个错误。

### ISSUE THREAD

**Issue by graytoowolf** [FalAut/sky1234#10]
[02Mar2024 21:38:00.939] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	Index: 9
	Listeners:
		0: HIGHEST
		1: ASM: io.github.noeppi_noeppi.libx.impl.config.ConfigEvents@4bf7399f serverPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		2: HIGH
		3: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		4: NORMAL
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@18b700f2
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@307af6ed
		7: ASM: class dev.architectury.networking.forge.NetworkManagerImpl loggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		8: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@5c48275c
		9: ASM: com.tkisor.upd8r.forge.event.JoinWorld@366b5ab1 joinWorldMessage(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		10: ASM: class dev.ftb.mods.ftbessentials.FTBEEventHandler playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		11: ASM: class moze_intel.projecte.events.PlayerEvents playerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		12: ASM: class moze_intel.projecte.events.PlayerEvents onHighAlchemistJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		13: ASM: class me.haydenb.assemblylinemachines.registry.config.ALMConfig$PreInit connectSendValidateRequest(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		14: ASM: codechicken.enderstorage.manager.EnderStorageManager$EnderStorageSaveHandler@2df5951b onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		15: ASM: codechicken.enderstorage.network.TankSynchroniser@21a52235 onPlayerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		16: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@815778b
		17: ASM: net.minecraftforge.common.ForgeInternalHandler@52fc03ae playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		18: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@288556eb
		19: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@4f2f0088
		20: ASM: class dev.ftb.extendedexchange.offline.OfflineKnowledgeManager$Listener onPlayerConnect(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		21: ASM: class com.forsteri.createendertransmission.CreateEnderTransmission$CommonEvents playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		22: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@5240bcf6
		23: ASM: class sonar.fluxnetworks.register.EventHandler onPlayerJoined(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		24: ASM: class blusunrize.immersiveengineering.common.blocks.multiblocks.StaticTemplateManager onLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		25: ASM: class com.simibubi.create.foundation.events.CommonEvents playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		26: ASM: class com.simibubi.create.content.equipment.extendoGrip.ExtendoGripItem addReachToJoiningPlayersHoldingExtendo(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		27: ASM: org.cyclops.cyclopscore.event.PlayerRingOfFire@1f05f0e onLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		28: ASM: top.theillusivec4.curios.common.event.CuriosEventHandler@4a751e2c playerLoggedIn(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		29: ASM: mekanism.common.CommonPlayerTracker@32a12f94 onPlayerLoginEvent(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		30: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@714a301a
		31: net.minecraftforge.eventbus.EventBus$$Lambda$1464/0x00007f30f0647a80@737a12d6
		32: LOWEST
		33: ASM: class capsule.loot.StarterLoot playerLogin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
		34: ASM: class de.melanx.skyblockbuilder.EventListener onPlayerJoin(Lnet/minecraftforge/event/entity/player/PlayerEvent$PlayerLoggedInEvent;)V
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.2.17/net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at TRANSFORMER/upd8r@1.18.2-1.1.0/com.tkisor.upd8r.util.InfoUtil.upd8rComponent(InfoUtil.java:17)
	at TRANSFORMER/upd8r@1.18.2-1.1.0/com.tkisor.upd8r.forge.event.JoinWorld.joinWorldMessage(JoinWorld.kt:21)
	at net.minecraftforge.eventbus.ASMEventHandler_202_JoinWorld_joinWorldMessage_PlayerLoggedInEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@40.2.17/net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:833)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:238)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.network.Connection.m_129483_(Connection.java:241)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261)
	at java.base/java.lang.Thread.run(Thread.java:833)

[02Mar2024 21:38:00.944] [Server thread/ERROR] [net.minecraft.server.network.ServerLoginPacketListenerImpl/]: Couldn't place player in world
java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
	at net.minecraftforge.fml.loading.RuntimeDistCleaner.processClassWithFlags(RuntimeDistCleaner.java:57) ~[fmlloader-1.18.2-40.2.17.jar%2318!/:1.0]
	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50) ~[modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219) ~[securejarhandler-1.0.8.jar:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.tkisor.upd8r.util.InfoUtil.upd8rComponent(InfoUtil.java:17) ~[Upd8r-1.18.2-1.1.0-forge.jar%23176!/:?]
	at com.tkisor.upd8r.forge.event.JoinWorld.joinWorldMessage(JoinWorld.kt:21) ~[Upd8r-1.18.2-1.1.0-forge.jar%23176!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler_202_JoinWorld_joinWorldMessage_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.event.ForgeEventFactory.firePlayerLoggedIn(ForgeEventFactory.java:833) ~[forge-1.18.2-40.2.17-universal.jar%23183!/:?]
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:238) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:241) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:916) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:326) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:842) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:685) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[server-1.18.2-20220404.173914-srg.jar%23178!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
	
下面是GPT给出的错误分析。
	这个错误表明在服务器端尝试加载了客户端的类 net.minecraft.client.Minecraft，但是在服务器端运行时这是无效的。在服务器端，应该使用服务器端的类和方法来处理玩家进入世界的逻辑。这个错误可能是由于代码中的一些混淆或错误的调用导致的。要解决这个问题，你需要检查你的代码并确保在服务器端使用正确的类和方法来处理玩家进入世界的逻辑。

**Comment by FalAut** [comment]
也许是服务端存在客户端模组的问题？试试我刚发到cf的服务端
https://legacy.curseforge.com/minecraft/modpacks/sky1234/files/5151391
经过测试，应该没有问题

**Comment by graytoowolf** [comment]
> 也许是服务端存在客户端模组的问题？试试我刚发到cf的服务端 https://legacy.curseforge.com/minecraft/modpacks/sky1234/files/5151391 经过测试，应该没有问题

能发一份到其他地方吗。cf审核好像很慢

**Comment by FalAut** [comment]
> 能发一份到其他地方吗。cf审核好像很慢

在github上发了一份
https://github.com/FalAut/sky1234/tree/serverpack

**Comment by graytoowolf** [comment]
> > 能发一份到其他地方吗。cf审核好像很慢
> 
> 在github上发了一份 https://github.com/FalAut/sky1234/tree/serverpack

可以了，能进服务器了。感谢
